from simics import *

cli.quiet_run_command('bp.console_string.break object = board.serconsole.con string = FAILED')
cli.quiet_run_command('bp.console_string.break object = board.serconsole.con string = Exception')
cli.quiet_run_command('bp.console_string.break object = board.serconsole.con string = ASSERT')
cli.quiet_run_command('bp.exception.break name = Overflow_Exception')
cli.quiet_run_command('bp.exception.break name = Stack_Fault_Exception')
cli.quiet_run_command('bp.exception.break name = SIMD_Floating_Point_Exception')
cli.quiet_run_command('bp.exception.break name = Page_Fault_Exception')
cli.quiet_run_command('bp.exception.break name = Alignment_Check_Exception')     
cli.quiet_run_command('bp.exception.break name = BOUND_Range_Exceeded_Exception ') 
cli.quiet_run_command('bp.exception.break name = Breakpoint_Exception')          
cli.quiet_run_command('bp.exception.break name = Control_Protection_Exception')  
cli.quiet_run_command('bp.exception.break name = Coprocessor_Segment_Overrun')    
cli.quiet_run_command('bp.exception.break name = Device_Not_Available_Exception') 
cli.quiet_run_command('bp.exception.break name = Divide_Error_Exception')          
cli.quiet_run_command('bp.exception.break name = Double_Fault_Exception')          
cli.quiet_run_command('bp.exception.break name = Floating_Point_Error_Exception')  
cli.quiet_run_command('bp.exception.break name = General_Protection_Exception')
cli.quiet_run_command('bp.exception.break name = Invalid_Opcode_Exception')
cli.quiet_run_command('bp.exception.break name = Invalid_TSS_Exception')
cli.quiet_run_command('bp.exception.break name = Machine_Check_Exception')
cli.quiet_run_command('bp.exception.break name = NMI_Interrupt')
cli.quiet_run_command('bp.exception.break name = Segment_Not_Present')
cli.quiet_run_command('bp.exception.break name = INT3')
cli.quiet_run_command('bp.exception.break name = Triple_Fault')       